# Generated by Django 2.1.13 on 2020-12-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('tid', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
            ],
            options={
                'db_table': 'token',
            },
        ),
    ]
