# Generated by Django 2.1.13 on 2020-12-12 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(1999, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='token',
            name='is_expire',
            field=models.BooleanField(default=False),
        ),
    ]
